name: Build and Test Decorators table history Library

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      # --- Optional Steps ---

      # Optional Step 7: Upload build artifacts.
      # This can be useful if you need to inspect the build output (the compiled JS files)
      # or use them in another job. The artifacts will be available for download from the workflow run page.
      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifacts-${{ matrix.node-version }}
      #     path: dist/ # The path to your build output directory, e.g., 'dist' or 'lib'
